import { Booking, Earning, OwnerProfile, ParkingListing, PaymentMethod, RenterBooking, RenterProfile } from '@/types';

export const ownerProfile: OwnerProfile = {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 (555) 123-4567',
    joinedDate: new Date('2024-03-15'),
    totalEarnings: 12847.50,
    activeListings: 3,
    rating: 4.8,
    reviewCount: 127,
    bankingSetup: true,
};

export const listings: ParkingListing[] = [
    {
        id: '1',
        title: 'Financial District Garage',
        address: '100 King St W, Toronto, ON',
        latitude: 43.6487,
        longitude: -79.3803,
        photos: [
            'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
            'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
        ],
        spaceType: 'garage',
        maxVehicleType: 'suv',
        hourlyRate: 12.50,
        dailyRate: 45.00,
        dimensions: '20ft x 10ft',
        accessType: 'code',
        accessInstructions: 'Enter code 4523 at the gate. Space B12 on level 2.',
        description: 'Prime underground parking in the heart of the Financial District. Direct access to PATH.',
        amenities: ['Covered', 'Security Camera', 'EV Charging', 'Well-lit', '24/7 Access'],
        status: 'active',
        totalEarnings: 5420.00,
        activeBookings: 2,
    },
    {
        id: '2',
        title: 'Rogers Centre Parking',
        address: '305 Bremner Blvd, Toronto, ON',
        latitude: 43.6418,
        longitude: -79.3891,
        photos: [
            'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
        ],
        spaceType: 'outdoor',
        maxVehicleType: 'truck',
        hourlyRate: 15.00,
        dailyRate: 60.00,
        accessType: 'app',
        accessInstructions: 'Use the app to unlock the gate. Row C, any available spot.',
        description: 'Steps from Rogers Centre and CN Tower. Perfect for game days and concerts.',
        amenities: ['Security Patrol', 'Oversized Spots', 'Event Pricing'],
        status: 'active',
        totalEarnings: 4327.50,
        activeBookings: 5,
    },
    {
        id: '3',
        title: 'Yonge & Dundas Square',
        address: '10 Dundas St E, Toronto, ON',
        latitude: 43.6561,
        longitude: -79.3802,
        photos: [
            'https://images.unsplash.com/photo-1486006920555-c77dcf18193e?w=800',
        ],
        spaceType: 'garage',
        maxVehicleType: 'sedan',
        hourlyRate: 10.00,
        dailyRate: 40.00,
        dimensions: '18ft x 9ft',
        accessType: 'open',
        description: 'Central location near Eaton Centre and theatres. Safe and secure.',
        amenities: ['Easy Access', 'Shopping Nearby', 'CCTV'],
        status: 'active',
        totalEarnings: 3100.00,
        activeBookings: 1,
    },
];

export const bookings: Booking[] = [
    {
        id: '1',
        listingId: '1',
        listingTitle: 'Financial District Garage',
        listingAddress: '100 King St W, Toronto, ON',
        renterName: 'John D.',
        renterInitials: 'JD',
        vehicleType: 'Tesla Model 3',
        startTime: new Date('2026-01-12T08:00:00'),
        endTime: new Date('2026-01-12T18:00:00'),
        totalAmount: 85.00,
        status: 'upcoming',
        paymentStatus: 'paid',
    },
    {
        id: '2',
        listingId: '1',
        listingTitle: 'Financial District Garage',
        listingAddress: '100 King St W, Toronto, ON',
        renterName: 'Emily R.',
        renterInitials: 'ER',
        vehicleType: 'Honda Accord',
        startTime: new Date('2026-01-15T07:00:00'),
        endTime: new Date('2026-01-15T19:00:00'),
        totalAmount: 102.00,
        status: 'upcoming',
        paymentStatus: 'paid',
    },
    {
        id: '3',
        listingId: '2',
        listingTitle: 'Rogers Centre Parking',
        listingAddress: '305 Bremner Blvd, Toronto, ON',
        renterName: 'Mike T.',
        renterInitials: 'MT',
        vehicleType: 'Toyota Camry',
        startTime: new Date('2026-01-11T06:00:00'),
        endTime: new Date('2026-01-18T20:00:00'),
        totalAmount: 175.00,
        status: 'active',
        paymentStatus: 'paid',
    },
    {
        id: '4',
        listingId: '3',
        listingTitle: 'Yonge & Dundas Square',
        listingAddress: '10 Dundas St E, Toronto, ON',
        renterName: 'Lisa K.',
        renterInitials: 'LK',
        vehicleType: 'BMW 3 Series',
        startTime: new Date('2026-01-08T10:00:00'),
        endTime: new Date('2026-01-08T22:00:00'),
        totalAmount: 72.00,
        status: 'Past',
        paymentStatus: 'paid',
    },
];

export const earnings: Earning[] = [
    {
        id: '1',
        date: new Date('2026-01-08'),
        bookingId: '4',
        amount: 72.00,
        status: 'pending',
    },
    {
        id: '2',
        date: new Date('2026-01-05'),
        bookingId: '5',
        amount: 145.00,
        status: 'paid',
        payoutDate: new Date('2026-01-07'),
    },
    {
        id: '3',
        date: new Date('2026-01-03'),
        bookingId: '6',
        amount: 95.00,
        status: 'paid',
        payoutDate: new Date('2026-01-07'),
    },
];

export const renterProfile: RenterProfile = {
    id: 'r1',
    name: 'Alex Thompson',
    email: 'alex.t@email.com',
    phone: '+1 (555) 987-6543',
    joinedDate: new Date('2025-08-20'),
    totalBookings: 24,
    rating: 4.9,
    reviewCount: 18,
};

export const renterBookings: RenterBooking[] = [
    {
        id: 'rb1',
        listingId: '1',
        listingTitle: 'Financial District Garage',
        listingAddress: '100 King St W, Toronto, ON',
        listingPhoto: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
        hostName: 'Sarah J.',
        hostRating: 4.8,
        licensePlate: 'ABC1234',
        vehicleType: 'Tesla Model 3',
        startTime: new Date('2026-01-14T08:00:00'),
        endTime: new Date('2026-01-14T18:00:00'),
        totalAmount: 85.00,
        status: 'upcoming',
        paymentStatus: 'paid',
        accessInstructions: 'Enter code 4523 at the gate. Space B12 on level 2.',
    },
    {
        id: 'rb2',
        listingId: '2',
        listingTitle: 'Rogers Centre Parking',
        listingAddress: '305 Bremner Blvd, Toronto, ON',
        listingPhoto: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
        hostName: 'Sarah J.',
        hostRating: 4.8,
        licensePlate: 'ABC1234',
        vehicleType: 'Tesla Model 3',
        startTime: new Date('2026-01-20T06:00:00'),
        endTime: new Date('2026-01-27T22:00:00'),
        totalAmount: 175.00,
        status: 'upcoming',
        paymentStatus: 'paid',
        accessInstructions: 'Use the app to unlock the gate. Row C, any available spot.',
    },
    {
        id: 'rb3',
        listingId: '3',
        listingTitle: 'Yonge & Dundas Square',
        listingAddress: '10 Dundas St E, Toronto, ON',
        listingPhoto: 'https://images.unsplash.com/photo-1486006920555-c77dcf18193e?w=800',
        hostName: 'Mike P.',
        hostRating: 4.6,
        licensePlate: 'ABC1234',
        vehicleType: 'Tesla Model 3',
        startTime: new Date('2026-01-05T10:00:00'),
        endTime: new Date('2026-01-05T22:00:00'),
        totalAmount: 72.00,
        status: 'Past',
        paymentStatus: 'paid',
    },
];

export const paymentMethods: PaymentMethod[] = [
    {
        id: 'pm1',
        type: 'card',
        last4: '4242',
        brand: 'Visa',
        expiryMonth: 12,
        expiryYear: 2027,
        isDefault: true,
    },
    {
        id: 'pm2',
        type: 'card',
        last4: '5555',
        brand: 'Mastercard',
        expiryMonth: 8,
        expiryYear: 2026,
        isDefault: false,
    },
];
